// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFb9DOcBO9ErRwNyEyvcwQQE92y3EI7TE',
    appId: '1:848536397462:web:859f8948f4c681a5a684b7',
    messagingSenderId: '848536397462',
    projectId: 'todo-list-ef9b6',
    authDomain: 'todo-list-ef9b6.firebaseapp.com',
    storageBucket: 'todo-list-ef9b6.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLykXl9T4lpH87JEUSfn4jwrg8MIKMxDM',
    appId: '1:848536397462:android:dfa5912a97901971a684b7',
    messagingSenderId: '848536397462',
    projectId: 'todo-list-ef9b6',
    storageBucket: 'todo-list-ef9b6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxm42ooaUEveFR5L9iopUxUZC8Nj43VrQ',
    appId: '1:848536397462:ios:fa9c6a65719a566ea684b7',
    messagingSenderId: '848536397462',
    projectId: 'todo-list-ef9b6',
    storageBucket: 'todo-list-ef9b6.appspot.com',
    iosBundleId: 'com.example.todoListApp',
  );
}
